"""new fields in user model

Revision ID: 951407e7f04e
Revises: a11ebbf7757a
Create Date: 2021-11-13 17:35:09.962147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951407e7f04e'
down_revision = 'a11ebbf7757a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
