"""add language to posts

Revision ID: d7651251331d
Revises: f16d3f4bf757
Create Date: 2021-11-27 20:33:31.187720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7651251331d'
down_revision = 'f16d3f4bf757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likers')
    op.drop_table('post_like')
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    op.drop_column('post', 'recipient_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('recipient_id', sa.INTEGER(), nullable=True))
    op.drop_column('post', 'language')
    op.create_table('post_like',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likers',
    sa.Column('liker_id', sa.INTEGER(), nullable=True),
    sa.Column('liked_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['liked_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['post.id'], )
    )
    # ### end Alembic commands ###
